/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as RequestDemoRouteImport } from './routes/request-demo'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsRiskRouteImport } from './routes/products.risk'
import { Route as ProductsRenewRouteImport } from './routes/products.renew'
import { Route as ProductsOnboardRouteImport } from './routes/products.onboard'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestDemoRoute = RequestDemoRouteImport.update({
  id: '/request-demo',
  path: '/request-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRiskRoute = ProductsRiskRouteImport.update({
  id: '/products/risk',
  path: '/products/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRenewRoute = ProductsRenewRouteImport.update({
  id: '/products/renew',
  path: '/products/renew',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsOnboardRoute = ProductsOnboardRouteImport.update({
  id: '/products/onboard',
  path: '/products/onboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/request-demo': typeof RequestDemoRoute
  '/signin': typeof SigninRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/products/onboard': typeof ProductsOnboardRoute
  '/products/renew': typeof ProductsRenewRoute
  '/products/risk': typeof ProductsRiskRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/request-demo': typeof RequestDemoRoute
  '/signin': typeof SigninRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/products/onboard': typeof ProductsOnboardRoute
  '/products/renew': typeof ProductsRenewRoute
  '/products/risk': typeof ProductsRiskRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/request-demo': typeof RequestDemoRoute
  '/signin': typeof SigninRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/products/onboard': typeof ProductsOnboardRoute
  '/products/renew': typeof ProductsRenewRoute
  '/products/risk': typeof ProductsRiskRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/request-demo'
    | '/signin'
    | '/sitemap.xml'
    | '/products/onboard'
    | '/products/renew'
    | '/products/risk'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/request-demo'
    | '/signin'
    | '/sitemap.xml'
    | '/products/onboard'
    | '/products/renew'
    | '/products/risk'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/request-demo'
    | '/signin'
    | '/sitemap.xml'
    | '/products/onboard'
    | '/products/renew'
    | '/products/risk'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  RequestDemoRoute: typeof RequestDemoRoute
  SigninRoute: typeof SigninRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ProductsOnboardRoute: typeof ProductsOnboardRoute
  ProductsRenewRoute: typeof ProductsRenewRoute
  ProductsRiskRoute: typeof ProductsRiskRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-demo': {
      id: '/request-demo'
      path: '/request-demo'
      fullPath: '/request-demo'
      preLoaderRoute: typeof RequestDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/risk': {
      id: '/products/risk'
      path: '/products/risk'
      fullPath: '/products/risk'
      preLoaderRoute: typeof ProductsRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/renew': {
      id: '/products/renew'
      path: '/products/renew'
      fullPath: '/products/renew'
      preLoaderRoute: typeof ProductsRenewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/onboard': {
      id: '/products/onboard'
      path: '/products/onboard'
      fullPath: '/products/onboard'
      preLoaderRoute: typeof ProductsOnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  RequestDemoRoute: RequestDemoRoute,
  SigninRoute: SigninRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ProductsOnboardRoute: ProductsOnboardRoute,
  ProductsRenewRoute: ProductsRenewRoute,
  ProductsRiskRoute: ProductsRiskRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
